# https://taskfile.dev

version: '3'

tasks:
  log-*:
    desc: Run a task with logging
    vars:
      TASK: "{{index .MATCH 0}}"
    cmds:
      - defer: echo '{{if .EXIT_CODE}}Failed with {{.EXIT_CODE}}!{{else}}Success!{{end}}'
      - task: _log-task-execution
        vars:
          TASK_NAME: "{{.TASK}}"

  _log-task-execution:
    desc: Log task execution
    cmds:
      - echo "Executing task {{.TASK_NAME}}"
      - task: "{{.TASK_NAME}}"

  test:
    desc: Test task
    cmds:
      - echo "This is a test task"
      - exit 0
    
  test-fail:
    desc: Test task that fails
    cmds:
      - echo "This is a test task that will fail"
      - exit 1