apiVersion: v1
kind: ConfigMap
metadata:
  name: skkg-settings
  namespace: qlever
data:
  skkg.settings.json: |
    { 
      "num-triples-per-batch": 1000000, 
      "parallel-parsing": false 
    }
