apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qlever-index-pvc
  namespace: qlever
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # storageClassName: do-block-storage
