# https://taskfile.dev

version: '3'

vars:
  BLAZEGRAPH_ENDPOINT: http://blazegraph:8080/blazegraph/sparql
  BLAZEGRAPH_ENDPOINT_SECONDARY: http://blazegraph-secondary:8080/blazegraph/sparql
  GENERATOR_POLICY: /mapping/generator-policy.xml
  MAPPING_BATCH_SIZE: 10

output: 'prefixed'

tasks:

  default:
    desc: Runs the entire pipeline
    cmds:
      - task: download-object-items

  download-address-items:
    desc: Download the address item records from MuseumPlus
    generates:
      - /data/source/addresses/*.xml
    vars:
      OUTPUT_FOLDER: /data/source/addresses
    cmds:
      - echo "Downloading address items from MuseumPlus"
      - mkdir -p {{.OUTPUT_FOLDER}}
      - task: _download-items-from-museumplus
        vars:
          MODULE: Address
          OUTPUT_FOLDER: "{{.OUTPUT_FOLDER}}"

  download-literature-items:
    desc: Download the literature item records from MuseumPlus
    generates:
      - /data/source/literature/*.xml
    vars:
      OUTPUT_FOLDER: /data/source/literature
    cmds:
      - echo "Downloading literature items from MuseumPlus"
      - mkdir -p {{.OUTPUT_FOLDER}}
      - task: _download-items-from-museumplus
        vars:
          MODULE: Literature
          OUTPUT_FOLDER: "{{.OUTPUT_FOLDER}}"

  download-object-items:
    desc: Download the object item records from MuseumPlus
    generates:
      - /data/source/objects/*.xml
    vars:
      OUTPUT_FOLDER: /data/source/objects
    cmds:
      - echo "Downloading object items from MuseumPlus"
      - mkdir -p {{.OUTPUT_FOLDER}}
      - task: _download-items-from-museumplus
        vars:
          MODULE: Object
          OUTPUT_FOLDER: "{{.OUTPUT_FOLDER}}"   

  _download-items-from-museumplus:
    vars:
      TEMP_FOLDER: /data/temp/temp_{{.MODULE}}
    cmds:
      - mkdir -p {{.TEMP_FOLDER}}
      - python /scripts/downloadItems.py --url $MUSEUMPLUS_URL --username $MUSEUMPLUS_USERNAME --password $MUSEUMPLUS_PASSWORD --module {{.MODULE}} --outputFolder {{.OUTPUT_FOLDER}} --tempFolder {{.TEMP_FOLDER}} {{.CLI_ARGS}}