# https://taskfile.dev

version: '3'

vars:
  BLAZEGRAPH_ENDPOINT: http://blazegraph:8080/blazegraph/sparql
  BLAZEGRAPH_ENDPOINT_SECONDARY: http://blazegraph-secondary:8080/blazegraph/sparql
  GENERATOR_POLICY: /mapping/generator-policy.xml
  MAPPING_BATCH_SIZE: 10

output: 'prefixed'

tasks:

  default:
    desc: Runs the entire pipeline
    cmds:
      - task: download-source-items

  download-source-items:
    desc: Downloads all item records from MuseumPlus
    deps:
      - download-address-items
      - download-literature-items
      - download-object-items
      - download-person-items

  download-address-items:
    desc: Download the address item records from MuseumPlus
    cmds:
      - task: _download-module-items-from-museumplus
        vars:
          MODULE: Address

  download-literature-items:
    desc: Download the literature item records from MuseumPlus
    cmds:
      - task: _download-module-items-from-museumplus
        vars:
          MODULE: Literature

  download-object-items:
    desc: Download the object item records from MuseumPlus
    cmds:
      - task: _download-module-items-from-museumplus
        vars:
          MODULE: Object

  download-person-items:
    desc: Download the person item records from MuseumPlus
    cmds:
      - task: _download-module-items-from-museumplus
        vars:
          MODULE: Person

  generate-example-record-object:
    desc: Generates an example record for developing the mapping in the X3ML editor
    vars:
      OUTPUTFILE: /mapping/example-object-record.xml
    cmds:
      - task: _generate-example-record
        vars:
          OUTPUTFILE: "{{.OUTPUTFILE}}"
          INPUTFILES: /data/source/object/object-item-0a0c96ab-71f1-466a-a5ff-ab556d437f15.xml /data/source/object/object-item-ffa356cf-f988-4d96-9580-92dcb0e4dddf.xml

  generate-example-record-person:
    desc: Generates an example record for developing the mapping in the X3ML editor
    vars:
      OUTPUTFILE: /mapping/example-person-record.xml
    cmds:
      - task: _generate-example-record
        vars:
          OUTPUTFILE: "{{.OUTPUTFILE}}"
          INPUTFILES: /data/source/person/person-item-0d2611a7-961e-420a-8b04-dc628c3f70fb.xml /data/source/person/person-item-f447a4d2-7be1-4d7c-8dcb-64381b20a9bc.xml
  
  perform-mapping-for-object-items:
    desc: Performs the mapping for the object items
    cmds:
      - task: _perform-mapping-for-module-items
        vars:
          MODULE: Object
  
  prepare-mapping-for-address-items:
    desc: Prepares the mapping for the object items
    cmds:
      - task: _prepare-mapping-for-module-items
        vars:
          MODULE: Address
  
  prepare-mapping-for-object-items:
    desc: Prepares the mapping for the object items
    cmds:
      - task: _prepare-mapping-for-module-items
        vars:
          MODULE: Object

  recreate-folder-metadata:
    desc: Recreate the metadata for a specific folder. The folder name should be passed as an argument.
    cmds:
      - python /scripts/updateMetadata.py --folder /data/source/{{.CLI_ARGS}}

  remove-deleted-address-items:
    desc: Removes address item records that have been deleted from MuseumPlus
    cmds:
      - task: _remove-deleted-module-items
        vars:
          MODULE: Address

  remove-deleted-literature-items:
    desc: Removes literature item records that have been deleted from MuseumPlus
    cmds:
      - task: _remove-deleted-module-items
        vars:
          MODULE: Literature

  remove-deleted-object-items:
    desc: Removes object item records that have been deleted from MuseumPlus
    cmds:
      - task: _remove-deleted-module-items
        vars:
          MODULE: Object

  remove-deleted-person-items:
    desc: Removes person item records that have been deleted from MuseumPlus
    cmds:
      - task: _remove-deleted-module-items
        vars:
          MODULE: Person

  remove-deleted-source-items:
    desc: Removes item records that have been deleted from MuseumPlus
    deps:
      - remove-deleted-address-items
      - remove-deleted-literature-items
      - remove-deleted-object-items
      - remove-deleted-person-items

  _download-module-items-from-museumplus:
    vars:
      FOLDER:
        sh: echo "/data/source/$(echo "{{.MODULE}}" | awk '{print tolower($0)}')"
      FILENAMEPREFIX:
        sh: echo "$(echo "{{.MODULE}}" | awk '{print tolower($0)}')-item-"
    cmds:
      - echo "Downloading {{.MODULE}} items from MuseumPlus"
      - mkdir -p {{.FOLDER}}
      - task: _download-items-from-museumplus
        vars:
          MODULE: "{{.MODULE}}"
          OUTPUT_FOLDER: "{{.FOLDER}}"
          FILENAMEPREFIX: "{{.FILENAMEPREFIX}}"

  _download-items-from-museumplus:
    vars:
      TEMP_FOLDER: /data/temp/temp_{{.MODULE}}
    cmds:
      - mkdir -p {{.TEMP_FOLDER}}
      - python /scripts/downloadItems.py --url $MUSEUMPLUS_URL --username $MUSEUMPLUS_USERNAME --password $MUSEUMPLUS_PASSWORD --module {{.MODULE}} --outputFolder {{.OUTPUT_FOLDER}} --tempFolder {{.TEMP_FOLDER}} --filenamePrefix {{.FILENAMEPREFIX}} {{.CLI_ARGS}}

  _generate-example-record:
    desc: Generates an example record for developing the mapping in the X3ML editor
    vars:
      OUTPUTFILE: "{{.OUTPUTFILE}}"
      INPUTFILES: "{{.INPUTFILES}}"
    cmds:
      - cat {{.INPUTFILES}} > {{.OUTPUTFILE}}
      - sed -i 's/<application xmlns="http:\/\/www.zetcom.com\/ria\/ws\/module">//g' {{.OUTPUTFILE}}
      - sed -i 's/<modules>//g' {{.OUTPUTFILE}}
      - sed -i 's/<\/modules>//g' {{.OUTPUTFILE}}
      - sed -i 's/<\/application>//g' {{.OUTPUTFILE}}
      - echo '<application><modules>' | cat - {{.OUTPUTFILE}} > temp && mv temp {{.OUTPUTFILE}}; echo '</modules></application>' >> {{.OUTPUTFILE}}

  _perform-mapping-for-module-items:
    vars:
      INPUTFOLDER:
        sh: echo "/data/mapping/input/$(echo "{{.MODULE}}" | awk '{print tolower($0)}')"
      OUTPUTFOLDER:
        sh: echo "/data/mapping/output/$(echo "{{.MODULE}}" | awk '{print tolower($0)}')"
      MAPPINGFILE:
        sh: echo "/mapping/mapping-$(echo "{{.MODULE}}" | awk '{print tolower($0)}').x3ml"
    cmds:
      - mkdir -p {{.OUTPUTFOLDER}}
      - rm -f {{.OUTPUTFOLDER}}/*.ttl
      - bash /scripts/performMapping.sh -i {{.INPUTFOLDER}} -o {{.OUTPUTFOLDER}} -m {{.MAPPINGFILE}} -g {{.GENERATOR_POLICY}} -b {{.MAPPING_BATCH_SIZE}}

  _prepare-mapping-for-module-items:
    vars:
      MODULE: "{{.MODULE}}"
      INPUTFOLDER:
        sh: echo "/data/source/$(echo "{{.MODULE}}" | awk '{print tolower($0)}')"
      OUTPUTFOLDER:
        sh: echo "/data/mapping/input/$(echo "{{.MODULE}}" | awk '{print tolower($0)}')"
    cmds:
      - mkdir -p {{.OUTPUTFOLDER}}
      - rm -f {{.OUTPUTFOLDER}}/*.xml
      - python /scripts/prepareDataForMapping.py --module {{.MODULE}} --inputFolder {{.INPUTFOLDER}} --outputFolder {{.OUTPUTFOLDER}} {{.CLI_ARGS}}

  _process-items-deleted-from-museumplus:
    cmds:
      - python /scripts/processDeletedItems.py --url $MUSEUMPLUS_URL --username $MUSEUMPLUS_USERNAME --password $MUSEUMPLUS_PASSWORD --module {{.MODULE}} --inputFolder {{.INPUT_FOLDER}} --filenamePrefix {{.FILENAMEPREFIX}}

  _remove-deleted-module-items:
    vars:
      FOLDER:
        sh: echo "/data/source/$(echo "{{.MODULE}}" | awk '{print tolower($0)}')"
      FILENAMEPREFIX:
        sh: echo "$(echo "{{.MODULE}}" | awk '{print tolower($0)}')-item-"
    cmds:
      - echo "Checking for deleted items in {{.MODULE}}"
      - task: _process-items-deleted-from-museumplus
        vars:
          MODULE: "{{.MODULE}}"
          INPUT_FOLDER: "{{.FOLDER}}"
          FILENAMEPREFIX: "{{.FILENAMEPREFIX}}"