# https://taskfile.dev

version: '3'

vars:
  BLAZEGRAPH_ENDPOINT: http://blazegraph:8080/blazegraph/sparql
  BLAZEGRAPH_ENDPOINT_SECONDARY: http://blazegraph-secondary:8080/blazegraph/sparql
  GENERATOR_POLICY: /mapping/generator-policy.xml
  MAPPING_BATCH_SIZE: 10

output: 'prefixed'

tasks:

  default:
    desc: Runs the entire pipeline
    cmds:
      - task: download-source-items

  
  download-source-items:
    desc: Download the item records from MuseumPlus
    source: 
      - scripts/downloadItems.py
    generates:
      - /data/source/*.xml
    vars:
      OUTPUT_FOLDER: /data/source
      DOTENV: /.env
    cmds:
      - python /scripts/downloadItems.py --url $MUSEUMPLUS_URL --username $MUSEUMPLUS_USERNAME --password $MUSEUMPLUS_PASSWORD --outputFolder {{.OUTPUT_FOLDER}} {{.CLI_ARGS}}