# https://taskfile.dev

version: '3'

vars:
  BLAZEGRAPH_ENDPOINT: http://blazegraph:8080/blazegraph/sparql
  BLAZEGRAPH_ENDPOINT_SECONDARY: http://blazegraph-secondary:8080/blazegraph/sparql
  GENERATOR_POLICY: /mapping/generator-policy.xml
  MAPPING_BATCH_SIZE: 10

output: 'prefixed'

tasks:

  default:
    desc: Runs the entire pipeline
    cmds:
      - task: download-source-items

  download-source-items:
    desc: Downloads all item records from MuseumPlus
    deps:
      - download-address-items
      - download-literature-items
      - download-object-items
      - download-person-items

  download-address-items:
    desc: Download the address item records from MuseumPlus
    cmds:
      - task: _download-module-items-from-museumplus
        vars:
          MODULE: Address

  download-literature-items:
    desc: Download the literature item records from MuseumPlus
    cmds:
      - task: _download-module-items-from-museumplus
        vars:
          MODULE: Literature

  download-object-items:
    desc: Download the object item records from MuseumPlus
    cmds:
      - task: _download-module-items-from-museumplus
        vars:
          MODULE: Object

  download-person-items:
    desc: Download the person item records from MuseumPlus
    cmds:
      - task: _download-module-items-from-museumplus
        vars:
          MODULE: Person

  recreate-folder-metadata:
    desc: Recreate the metadata for a specific folder. The folder name should be passed as an argument.
    cmds:
      - python /scripts/updateMetadata.py --folder /data/source/{{.CLI_ARGS}}

  remove-deleted-address-items:
    desc: Removes address item records that have been deleted from MuseumPlus
    cmds:
      - task: _remove-deleted-module-items
        vars:
          MODULE: Address

  remove-deleted-literature-items:
    desc: Removes literature item records that have been deleted from MuseumPlus
    cmds:
      - task: _remove-deleted-module-items
        vars:
          MODULE: Literature

  remove-deleted-object-items:
    desc: Removes object item records that have been deleted from MuseumPlus
    cmds:
      - task: _remove-deleted-module-items
        vars:
          MODULE: Object

  remove-deleted-person-items:
    desc: Removes person item records that have been deleted from MuseumPlus
    cmds:
      - task: _remove-deleted-module-items
        vars:
          MODULE: Person

  remove-deleted-source-items:
    desc: Removes item records that have been deleted from MuseumPlus
    deps:
      - remove-deleted-address-items
      - remove-deleted-literature-items
      - remove-deleted-object-items
      - remove-deleted-person-items

  _download-module-items-from-museumplus:
    vars:
      FOLDER:
        sh: echo "/data/source/$(echo "{{.MODULE}}" | awk '{print tolower($0)}')"
      FILENAMEPREFIX:
        sh: echo "$(echo "{{.MODULE}}" | awk '{print tolower($0)}')-item-"
    cmds:
      - echo "Downloading {{.MODULE}} items from MuseumPlus"
      - mkdir -p {{.FOLDER}}
      - task: _download-items-from-museumplus
        vars:
          MODULE: "{{.MODULE}}"
          OUTPUT_FOLDER: "{{.FOLDER}}"
          FILENAMEPREFIX: "{{.FILENAMEPREFIX}}"
      - echo "Checking for deleted items"
      - task: _process-items-deleted-from-museumplus
        vars:
          MODULE: "{{.MODULE}}"
          INPUT_FOLDER: "{{.FOLDER}}"
          FILENAMEPREFIX: "{{.FILENAMEPREFIX}}"

  _download-items-from-museumplus:
    vars:
      TEMP_FOLDER: /data/temp/temp_{{.MODULE}}
    cmds:
      - mkdir -p {{.TEMP_FOLDER}}
      - python /scripts/downloadItems.py --url $MUSEUMPLUS_URL --username $MUSEUMPLUS_USERNAME --password $MUSEUMPLUS_PASSWORD --module {{.MODULE}} --outputFolder {{.OUTPUT_FOLDER}} --tempFolder {{.TEMP_FOLDER}} --filenamePrefix {{.FILENAMEPREFIX}} {{.CLI_ARGS}}

  _process-items-deleted-from-museumplus:
    cmds:
      - python /scripts/processDeletedItems.py --url $MUSEUMPLUS_URL --username $MUSEUMPLUS_USERNAME --password $MUSEUMPLUS_PASSWORD --module {{.MODULE}} --inputFolder {{.INPUT_FOLDER}} --filenamePrefix {{.FILENAMEPREFIX}}

  _remove-deleted-module-items:
    vars:
      FOLDER:
        sh: echo "/data/source/$(echo "{{.MODULE}}" | awk '{print tolower($0)}')"
      FILENAMEPREFIX:
        sh: echo "$(echo "{{.MODULE}}" | awk '{print tolower($0)}')-item-"
    cmds:
      - echo "Checking for deleted items in {{.MODULE}}"
      - task: _process-items-deleted-from-museumplus
        vars:
          MODULE: "{{.MODULE}}"
          INPUT_FOLDER: "{{.FOLDER}}"
          FILENAMEPREFIX: "{{.FILENAMEPREFIX}}"