name: Run pipeline task on STAGING

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Which task would you like to run?
        options:
          - default
          - run-pipeline-cycles
          - update-vocabularies
          - update-iiif

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: SSH into server and run pipeline
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST_STAGING }}
        username: ${{ secrets.SSH_USER_STAGING }}
        key: ${{ secrets.DEPLOY_KEY_STAGING }}
        command_timeout: 200m
        script: |
          cd ${{ secrets.DEPLOY_PATH_STAGING }}
          git pull
          cd services/platform/apps/skkg
          git pull
          cd ${{ secrets.DEPLOY_PATH_STAGING }}
          docker compose exec jobs task
